/*
 * Quickstart API Reference
 *
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.   To use the Quickstart API, you must have the following features enabled on your tenant:   * [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)  * [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)  To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://www.zuora.com/developer/quickstart-api/changelog/2022q4-changelog/).  We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.  
 *
 * The version of the OpenAPI document: 2023-09-25
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Zuora.Client.OpenAPIDateConverter;

namespace Zuora.Model
{
    /// <summary>
    /// FulfillmentCreateBulkResponse
    /// </summary>
    [DataContract]
    public partial class FulfillmentCreateBulkResponse :  IEquatable<FulfillmentCreateBulkResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentCreateBulkResponse" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="amountPaid">The total amount collected by this request..</param>
        /// <param name="paymentNumber">Human-readable identifier of the payment associated with this fulfillment..</param>
        /// <param name="creditMemoNumbers">Human-readable identifiers of any credit memos associated with this request..</param>
        /// <param name="invoiceNumbers">Human-readable identifiers of any invoices associated with this request..</param>
        public FulfillmentCreateBulkResponse(List<Fulfillment> data = default(List<Fulfillment>), decimal amountPaid = default(decimal), string paymentNumber = default(string), List<string> creditMemoNumbers = default(List<string>), List<string> invoiceNumbers = default(List<string>))
        {
            this.data = data;
            this.amount_paid = amountPaid;
            this.payment_number = paymentNumber;
            this.credit_memo_numbers = creditMemoNumbers;
            this.invoice_numbers = invoiceNumbers;
        }

        /// <summary>
        /// Gets or Sets data
        /// </summary>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public List<Fulfillment> data { get; set; }

        /// <summary>
        /// The total amount collected by this request.
        /// </summary>
        /// <value>The total amount collected by this request.</value>
        [DataMember(Name="amount_paid", EmitDefaultValue=false)]
        public decimal amount_paid { get; set; }

        /// <summary>
        /// Human-readable identifier of the payment associated with this fulfillment.
        /// </summary>
        /// <value>Human-readable identifier of the payment associated with this fulfillment.</value>
        [DataMember(Name="payment_number", EmitDefaultValue=false)]
        public string payment_number { get; set; }

        /// <summary>
        /// Human-readable identifiers of any credit memos associated with this request.
        /// </summary>
        /// <value>Human-readable identifiers of any credit memos associated with this request.</value>
        [DataMember(Name="credit_memo_numbers", EmitDefaultValue=false)]
        public List<string> credit_memo_numbers { get; set; }

        /// <summary>
        /// Human-readable identifiers of any invoices associated with this request.
        /// </summary>
        /// <value>Human-readable identifiers of any invoices associated with this request.</value>
        [DataMember(Name="invoice_numbers", EmitDefaultValue=false)]
        public List<string> invoice_numbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FulfillmentCreateBulkResponse {\n");
            sb.Append("  data: ").Append(data).Append("\n");
            sb.Append("  amount_paid: ").Append(amount_paid).Append("\n");
            sb.Append("  payment_number: ").Append(payment_number).Append("\n");
            sb.Append("  credit_memo_numbers: ").Append(credit_memo_numbers).Append("\n");
            sb.Append("  invoice_numbers: ").Append(invoice_numbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FulfillmentCreateBulkResponse);
        }

        /// <summary>
        /// Returns true if FulfillmentCreateBulkResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of FulfillmentCreateBulkResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FulfillmentCreateBulkResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.data == input.data ||
                    this.data != null &&
                    input.data != null &&
                    this.data.SequenceEqual(input.data)
                ) && 
                (
                    this.amount_paid == input.amount_paid ||
                    (this.amount_paid != null &&
                    this.amount_paid.Equals(input.amount_paid))
                ) && 
                (
                    this.payment_number == input.payment_number ||
                    (this.payment_number != null &&
                    this.payment_number.Equals(input.payment_number))
                ) && 
                (
                    this.credit_memo_numbers == input.credit_memo_numbers ||
                    this.credit_memo_numbers != null &&
                    input.credit_memo_numbers != null &&
                    this.credit_memo_numbers.SequenceEqual(input.credit_memo_numbers)
                ) && 
                (
                    this.invoice_numbers == input.invoice_numbers ||
                    this.invoice_numbers != null &&
                    input.invoice_numbers != null &&
                    this.invoice_numbers.SequenceEqual(input.invoice_numbers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.data != null)
                    hashCode = hashCode * 59 + this.data.GetHashCode();
                if (this.amount_paid != null)
                    hashCode = hashCode * 59 + this.amount_paid.GetHashCode();
                if (this.payment_number != null)
                    hashCode = hashCode * 59 + this.payment_number.GetHashCode();
                if (this.credit_memo_numbers != null)
                    hashCode = hashCode * 59 + this.credit_memo_numbers.GetHashCode();
                if (this.invoice_numbers != null)
                    hashCode = hashCode * 59 + this.invoice_numbers.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
