/*
 * Quickstart API Reference
 *
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.   To use the Quickstart API, you must have the following features enabled on your tenant:   * [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)  * [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)  To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://www.zuora.com/developer/quickstart-api/changelog/2022q4-changelog/).  We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.  
 *
 * The version of the OpenAPI document: 2023-09-25
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zuora.Api;
using Zuora.Model;
using Zuora.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zuora.Test
{
    /// <summary>
    ///  Class for testing BillRun
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillRunTests
    {
        // TODO uncomment below to declare an instance variable for BillRun
        //private BillRun instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillRun
            //instance = new BillRun();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillRun
        /// </summary>
        [Test]
        public void BillRunInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" BillRun
            //Assert.IsInstanceOf(typeof(BillRun), instance);
        }


        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'updated_by_id'
        /// </summary>
        [Test]
        public void updated_by_idTest()
        {
            // TODO unit test for the property 'updated_by_id'
        }
        /// <summary>
        /// Test the property 'updated_time'
        /// </summary>
        [Test]
        public void updated_timeTest()
        {
            // TODO unit test for the property 'updated_time'
        }
        /// <summary>
        /// Test the property 'created_by_id'
        /// </summary>
        [Test]
        public void created_by_idTest()
        {
            // TODO unit test for the property 'created_by_id'
        }
        /// <summary>
        /// Test the property 'created_time'
        /// </summary>
        [Test]
        public void created_timeTest()
        {
            // TODO unit test for the property 'created_time'
        }
        /// <summary>
        /// Test the property 'custom_fields'
        /// </summary>
        [Test]
        public void custom_fieldsTest()
        {
            // TODO unit test for the property 'custom_fields'
        }
        /// <summary>
        /// Test the property 'custom_objects'
        /// </summary>
        [Test]
        public void custom_objectsTest()
        {
            // TODO unit test for the property 'custom_objects'
        }
        /// <summary>
        /// Test the property 'account_id'
        /// </summary>
        [Test]
        public void account_idTest()
        {
            // TODO unit test for the property 'account_id'
        }
        /// <summary>
        /// Test the property 'email'
        /// </summary>
        [Test]
        public void emailTest()
        {
            // TODO unit test for the property 'email'
        }
        /// <summary>
        /// Test the property 'post'
        /// </summary>
        [Test]
        public void postTest()
        {
            // TODO unit test for the property 'post'
        }
        /// <summary>
        /// Test the property 'renew'
        /// </summary>
        [Test]
        public void renewTest()
        {
            // TODO unit test for the property 'renew'
        }
        /// <summary>
        /// Test the property 'day_of_month'
        /// </summary>
        [Test]
        public void day_of_monthTest()
        {
            // TODO unit test for the property 'day_of_month'
        }
        /// <summary>
        /// Test the property 'bill_run_number'
        /// </summary>
        [Test]
        public void bill_run_numberTest()
        {
            // TODO unit test for the property 'bill_run_number'
        }
        /// <summary>
        /// Test the property 'bill_run_time'
        /// </summary>
        [Test]
        public void bill_run_timeTest()
        {
            // TODO unit test for the property 'bill_run_time'
        }
        /// <summary>
        /// Test the property 'invoice_date'
        /// </summary>
        [Test]
        public void invoice_dateTest()
        {
            // TODO unit test for the property 'invoice_date'
        }
        /// <summary>
        /// Test the property 'target_date'
        /// </summary>
        [Test]
        public void target_dateTest()
        {
            // TODO unit test for the property 'target_date'
        }
        /// <summary>
        /// Test the property 'state'
        /// </summary>
        [Test]
        public void stateTest()
        {
            // TODO unit test for the property 'state'
        }
        /// <summary>
        /// Test the property 'batches'
        /// </summary>
        [Test]
        public void batchesTest()
        {
            // TODO unit test for the property 'batches'
        }
        /// <summary>
        /// Test the property 'charges_excluded'
        /// </summary>
        [Test]
        public void charges_excludedTest()
        {
            // TODO unit test for the property 'charges_excluded'
        }
        /// <summary>
        /// Test the property 'email_zero_amount_invoices'
        /// </summary>
        [Test]
        public void email_zero_amount_invoicesTest()
        {
            // TODO unit test for the property 'email_zero_amount_invoices'
        }
        /// <summary>
        /// Test the property 'invoices_sent'
        /// </summary>
        [Test]
        public void invoices_sentTest()
        {
            // TODO unit test for the property 'invoices_sent'
        }
        /// <summary>
        /// Test the property 'last_invoice_sent_time'
        /// </summary>
        [Test]
        public void last_invoice_sent_timeTest()
        {
            // TODO unit test for the property 'last_invoice_sent_time'
        }
        /// <summary>
        /// Test the property 'accounts_processed'
        /// </summary>
        [Test]
        public void accounts_processedTest()
        {
            // TODO unit test for the property 'accounts_processed'
        }
        /// <summary>
        /// Test the property 'invoices_generated'
        /// </summary>
        [Test]
        public void invoices_generatedTest()
        {
            // TODO unit test for the property 'invoices_generated'
        }
        /// <summary>
        /// Test the property 'credit_memos_generated'
        /// </summary>
        [Test]
        public void credit_memos_generatedTest()
        {
            // TODO unit test for the property 'credit_memos_generated'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }

    }

}
