/*
 * Quickstart API Reference
 *
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.   To use the Quickstart API, you must have the following features enabled on your tenant:   * [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)  * [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)  To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://www.zuora.com/developer/quickstart-api/changelog/2022q4-changelog/).  We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.  
 *
 * The version of the OpenAPI document: 2023-09-25
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zuora.Api;
using Zuora.Model;
using Zuora.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zuora.Test
{
    /// <summary>
    ///  Class for testing OrderLineItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderLineItemTests
    {
        // TODO uncomment below to declare an instance variable for OrderLineItem
        //private OrderLineItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderLineItem
            //instance = new OrderLineItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderLineItem
        /// </summary>
        [Test]
        public void OrderLineItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" OrderLineItem
            //Assert.IsInstanceOf(typeof(OrderLineItem), instance);
        }


        /// <summary>
        /// Test the property 'id'
        /// </summary>
        [Test]
        public void idTest()
        {
            // TODO unit test for the property 'id'
        }
        /// <summary>
        /// Test the property 'updated_by_id'
        /// </summary>
        [Test]
        public void updated_by_idTest()
        {
            // TODO unit test for the property 'updated_by_id'
        }
        /// <summary>
        /// Test the property 'updated_time'
        /// </summary>
        [Test]
        public void updated_timeTest()
        {
            // TODO unit test for the property 'updated_time'
        }
        /// <summary>
        /// Test the property 'created_by_id'
        /// </summary>
        [Test]
        public void created_by_idTest()
        {
            // TODO unit test for the property 'created_by_id'
        }
        /// <summary>
        /// Test the property 'created_time'
        /// </summary>
        [Test]
        public void created_timeTest()
        {
            // TODO unit test for the property 'created_time'
        }
        /// <summary>
        /// Test the property 'custom_fields'
        /// </summary>
        [Test]
        public void custom_fieldsTest()
        {
            // TODO unit test for the property 'custom_fields'
        }
        /// <summary>
        /// Test the property 'custom_objects'
        /// </summary>
        [Test]
        public void custom_objectsTest()
        {
            // TODO unit test for the property 'custom_objects'
        }
        /// <summary>
        /// Test the property 'revenue'
        /// </summary>
        [Test]
        public void revenueTest()
        {
            // TODO unit test for the property 'revenue'
        }
        /// <summary>
        /// Test the property 'unit_of_measure'
        /// </summary>
        [Test]
        public void unit_of_measureTest()
        {
            // TODO unit test for the property 'unit_of_measure'
        }
        /// <summary>
        /// Test the property 'accounting_code'
        /// </summary>
        [Test]
        public void accounting_codeTest()
        {
            // TODO unit test for the property 'accounting_code'
        }
        /// <summary>
        /// Test the property 'adjustment_liability_account'
        /// </summary>
        [Test]
        public void adjustment_liability_accountTest()
        {
            // TODO unit test for the property 'adjustment_liability_account'
        }
        /// <summary>
        /// Test the property 'unit_amount'
        /// </summary>
        [Test]
        public void unit_amountTest()
        {
            // TODO unit test for the property 'unit_amount'
        }
        /// <summary>
        /// Test the property 'target_date'
        /// </summary>
        [Test]
        public void target_dateTest()
        {
            // TODO unit test for the property 'target_date'
        }
        /// <summary>
        /// Test the property 'billing_rule'
        /// </summary>
        [Test]
        public void billing_ruleTest()
        {
            // TODO unit test for the property 'billing_rule'
        }
        /// <summary>
        /// Test the property 'contract_asset_account'
        /// </summary>
        [Test]
        public void contract_asset_accountTest()
        {
            // TODO unit test for the property 'contract_asset_account'
        }
        /// <summary>
        /// Test the property 'contract_liability_account'
        /// </summary>
        [Test]
        public void contract_liability_accountTest()
        {
            // TODO unit test for the property 'contract_liability_account'
        }
        /// <summary>
        /// Test the property 'description'
        /// </summary>
        [Test]
        public void descriptionTest()
        {
            // TODO unit test for the property 'description'
        }
        /// <summary>
        /// Test the property 'discount_unit_amount'
        /// </summary>
        [Test]
        public void discount_unit_amountTest()
        {
            // TODO unit test for the property 'discount_unit_amount'
        }
        /// <summary>
        /// Test the property 'discount_percent'
        /// </summary>
        [Test]
        public void discount_percentTest()
        {
            // TODO unit test for the property 'discount_percent'
        }
        /// <summary>
        /// Test the property 'category'
        /// </summary>
        [Test]
        public void categoryTest()
        {
            // TODO unit test for the property 'category'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'type'
        /// </summary>
        [Test]
        public void typeTest()
        {
            // TODO unit test for the property 'type'
        }
        /// <summary>
        /// Test the property 'list_unit_price'
        /// </summary>
        [Test]
        public void list_unit_priceTest()
        {
            // TODO unit test for the property 'list_unit_price'
        }
        /// <summary>
        /// Test the property 'product_code'
        /// </summary>
        [Test]
        public void product_codeTest()
        {
            // TODO unit test for the property 'product_code'
        }
        /// <summary>
        /// Test the property 'purchase_order_number'
        /// </summary>
        [Test]
        public void purchase_order_numberTest()
        {
            // TODO unit test for the property 'purchase_order_number'
        }
        /// <summary>
        /// Test the property 'quantity'
        /// </summary>
        [Test]
        public void quantityTest()
        {
            // TODO unit test for the property 'quantity'
        }
        /// <summary>
        /// Test the property 'related_subscription_number'
        /// </summary>
        [Test]
        public void related_subscription_numberTest()
        {
            // TODO unit test for the property 'related_subscription_number'
        }
        /// <summary>
        /// Test the property 'sold_to_id'
        /// </summary>
        [Test]
        public void sold_to_idTest()
        {
            // TODO unit test for the property 'sold_to_id'
        }
        /// <summary>
        /// Test the property 'tax_code'
        /// </summary>
        [Test]
        public void tax_codeTest()
        {
            // TODO unit test for the property 'tax_code'
        }
        /// <summary>
        /// Test the property 'unbilled_receivables_account'
        /// </summary>
        [Test]
        public void unbilled_receivables_accountTest()
        {
            // TODO unit test for the property 'unbilled_receivables_account'
        }
        /// <summary>
        /// Test the property 'state'
        /// </summary>
        [Test]
        public void stateTest()
        {
            // TODO unit test for the property 'state'
        }
        /// <summary>
        /// Test the property 'item_number'
        /// </summary>
        [Test]
        public void item_numberTest()
        {
            // TODO unit test for the property 'item_number'
        }
        /// <summary>
        /// Test the property 'start_date'
        /// </summary>
        [Test]
        public void start_dateTest()
        {
            // TODO unit test for the property 'start_date'
        }
        /// <summary>
        /// Test the property 'end_date'
        /// </summary>
        [Test]
        public void end_dateTest()
        {
            // TODO unit test for the property 'end_date'
        }
        /// <summary>
        /// Test the property 'price_id'
        /// </summary>
        [Test]
        public void price_idTest()
        {
            // TODO unit test for the property 'price_id'
        }
        /// <summary>
        /// Test the property 'quantity_available_for_return'
        /// </summary>
        [Test]
        public void quantity_available_for_returnTest()
        {
            // TODO unit test for the property 'quantity_available_for_return'
        }
        /// <summary>
        /// Test the property 'tax_inclusive'
        /// </summary>
        [Test]
        public void tax_inclusiveTest()
        {
            // TODO unit test for the property 'tax_inclusive'
        }
        /// <summary>
        /// Test the property 'invoice_items'
        /// </summary>
        [Test]
        public void invoice_itemsTest()
        {
            // TODO unit test for the property 'invoice_items'
        }
        /// <summary>
        /// Test the property 'order_id'
        /// </summary>
        [Test]
        public void order_idTest()
        {
            // TODO unit test for the property 'order_id'
        }
        /// <summary>
        /// Test the property 'total'
        /// </summary>
        [Test]
        public void totalTest()
        {
            // TODO unit test for the property 'total'
        }
        /// <summary>
        /// Test the property 'subtotal'
        /// </summary>
        [Test]
        public void subtotalTest()
        {
            // TODO unit test for the property 'subtotal'
        }
        /// <summary>
        /// Test the property 'quantity_fulfilled'
        /// </summary>
        [Test]
        public void quantity_fulfilledTest()
        {
            // TODO unit test for the property 'quantity_fulfilled'
        }
        /// <summary>
        /// Test the property 'quantity_pending_fulfillment'
        /// </summary>
        [Test]
        public void quantity_pending_fulfillmentTest()
        {
            // TODO unit test for the property 'quantity_pending_fulfillment'
        }
        /// <summary>
        /// Test the property 'requires_fulfillment'
        /// </summary>
        [Test]
        public void requires_fulfillmentTest()
        {
            // TODO unit test for the property 'requires_fulfillment'
        }
        /// <summary>
        /// Test the property 'original_order_date'
        /// </summary>
        [Test]
        public void original_order_dateTest()
        {
            // TODO unit test for the property 'original_order_date'
        }
        /// <summary>
        /// Test the property 'original_order_id'
        /// </summary>
        [Test]
        public void original_order_idTest()
        {
            // TODO unit test for the property 'original_order_id'
        }
        /// <summary>
        /// Test the property 'original_order_line_item_id'
        /// </summary>
        [Test]
        public void original_order_line_item_idTest()
        {
            // TODO unit test for the property 'original_order_line_item_id'
        }
        /// <summary>
        /// Test the property 'original_order_line_item_number'
        /// </summary>
        [Test]
        public void original_order_line_item_numberTest()
        {
            // TODO unit test for the property 'original_order_line_item_number'
        }
        /// <summary>
        /// Test the property 'original_order_number'
        /// </summary>
        [Test]
        public void original_order_numberTest()
        {
            // TODO unit test for the property 'original_order_number'
        }
        /// <summary>
        /// Test the property 'discount_total'
        /// </summary>
        [Test]
        public void discount_totalTest()
        {
            // TODO unit test for the property 'discount_total'
        }
        /// <summary>
        /// Test the property 'list_price'
        /// </summary>
        [Test]
        public void list_priceTest()
        {
            // TODO unit test for the property 'list_price'
        }
        /// <summary>
        /// Test the property 'original_sold_to_id'
        /// </summary>
        [Test]
        public void original_sold_to_idTest()
        {
            // TODO unit test for the property 'original_sold_to_id'
        }

    }

}
